# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170530_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='truncate_words',
            field=models.IntegerField(default=50),
        ),
    ]
